name: project_netsurf
description: Much more from nature

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.1.0+52

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  synchronized: ^3.1.0
  pdf: ^3.10.7
  open_app_file: ^4.0.1
  path_provider: ^2.1.3
  intl: ^0.19.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.5.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.2
  flutter_phoenix: ^1.1.1
  share_plus: ^7.2.2
  firebase_analytics: ^11.3.3
  carousel_slider: ^5.1.1
  device_info_plus: ^10.1.0
  get_it: ^7.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/banner.png

#dev_dependencies:
#  flutter_native_splash: ^2.4.0
#  flutter_launcher_icons: ^0.13.1
##  flutter_app_name: ^0.1.0
#  flutter_lints: ^4.0.0

#flutter_native_splash:
#  color: "#ffffff"
#  image: assets/banner.png
#  android: true
#  ios: true
#  web: true
## flutter pub run flutter_native_splash:create
#
#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/banner.png"
## flutter pub run flutter_launcher_icons:main
#
#flutter_launcher_name:
#  name: "Netsurfs Calci"
## flutter pub run flutter_app_name
